version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "oprearocks"
      POSTGRES_PASSWORD: "Who dis?"
    ports:
      - 5432:5432
    volumes:
      - ./docker-storage/postgresql-data:/var/lib/postgresql/data
